//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("houseofgModel", "FK_AMIGOS_AGREGAN_USUARIOS", "USUARIOS", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcHouseofg.Models.USUARIOS), "AMIGOS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcHouseofg.Models.AMIGOS), true)]
[assembly: EdmRelationshipAttribute("houseofgModel", "FK_CUENTAS_CONTIENEN_TIPOS_CU", "TIPOS_CUENTA", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcHouseofg.Models.TIPOS_CUENTA), "CUENTAS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcHouseofg.Models.CUENTAS), true)]
[assembly: EdmRelationshipAttribute("houseofgModel", "FK_CUENTAS_CREAN_USUARIOS", "USUARIOS", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcHouseofg.Models.USUARIOS), "CUENTAS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcHouseofg.Models.CUENTAS), true)]
[assembly: EdmRelationshipAttribute("houseofgModel", "FK_DETALLES_GENERAN_PRODUCTO", "PRODUCTOS", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcHouseofg.Models.PRODUCTOS), "DETALLES", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcHouseofg.Models.DETALLES), true)]
[assembly: EdmRelationshipAttribute("houseofgModel", "FK_DETALLES_POSEE_PEDIDOS", "PEDIDOS", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcHouseofg.Models.PEDIDOS), "DETALLES", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcHouseofg.Models.DETALLES), true)]
[assembly: EdmRelationshipAttribute("houseofgModel", "FK_PEDIDOS_REALIZA_USUARIOS", "USUARIOS", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcHouseofg.Models.USUARIOS), "PEDIDOS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcHouseofg.Models.PEDIDOS), true)]
[assembly: EdmRelationshipAttribute("houseofgModel", "FK_VALORACI_TIENEN_PRODUCTO", "PRODUCTOS", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MvcHouseofg.Models.PRODUCTOS), "VALORACIONES", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcHouseofg.Models.VALORACIONES), true)]
[assembly: EdmRelationshipAttribute("houseofgModel", "FK_VALORACI_REALIZAN_USUARIOS", "USUARIOS", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MvcHouseofg.Models.USUARIOS), "VALORACIONES", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcHouseofg.Models.VALORACIONES), true)]

#endregion

namespace MvcHouseofg.Models
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class houseofgEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto houseofgEntities usando la cadena de conexión encontrada en la sección 'houseofgEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public houseofgEntities() : base("name=houseofgEntities", "houseofgEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto houseofgEntities.
        /// </summary>
        public houseofgEntities(string connectionString) : base(connectionString, "houseofgEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto houseofgEntities.
        /// </summary>
        public houseofgEntities(EntityConnection connection) : base(connection, "houseofgEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<AMIGOS> AMIGOS
        {
            get
            {
                if ((_AMIGOS == null))
                {
                    _AMIGOS = base.CreateObjectSet<AMIGOS>("AMIGOS");
                }
                return _AMIGOS;
            }
        }
        private ObjectSet<AMIGOS> _AMIGOS;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<CUENTAS> CUENTAS
        {
            get
            {
                if ((_CUENTAS == null))
                {
                    _CUENTAS = base.CreateObjectSet<CUENTAS>("CUENTAS");
                }
                return _CUENTAS;
            }
        }
        private ObjectSet<CUENTAS> _CUENTAS;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<DETALLES> DETALLES
        {
            get
            {
                if ((_DETALLES == null))
                {
                    _DETALLES = base.CreateObjectSet<DETALLES>("DETALLES");
                }
                return _DETALLES;
            }
        }
        private ObjectSet<DETALLES> _DETALLES;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<PEDIDOS> PEDIDOS
        {
            get
            {
                if ((_PEDIDOS == null))
                {
                    _PEDIDOS = base.CreateObjectSet<PEDIDOS>("PEDIDOS");
                }
                return _PEDIDOS;
            }
        }
        private ObjectSet<PEDIDOS> _PEDIDOS;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<PRODUCTOS> PRODUCTOS
        {
            get
            {
                if ((_PRODUCTOS == null))
                {
                    _PRODUCTOS = base.CreateObjectSet<PRODUCTOS>("PRODUCTOS");
                }
                return _PRODUCTOS;
            }
        }
        private ObjectSet<PRODUCTOS> _PRODUCTOS;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<TIPOS_CUENTA> TIPOS_CUENTA
        {
            get
            {
                if ((_TIPOS_CUENTA == null))
                {
                    _TIPOS_CUENTA = base.CreateObjectSet<TIPOS_CUENTA>("TIPOS_CUENTA");
                }
                return _TIPOS_CUENTA;
            }
        }
        private ObjectSet<TIPOS_CUENTA> _TIPOS_CUENTA;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<USUARIOS> USUARIOS
        {
            get
            {
                if ((_USUARIOS == null))
                {
                    _USUARIOS = base.CreateObjectSet<USUARIOS>("USUARIOS");
                }
                return _USUARIOS;
            }
        }
        private ObjectSet<USUARIOS> _USUARIOS;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<VALORACIONES> VALORACIONES
        {
            get
            {
                if ((_VALORACIONES == null))
                {
                    _VALORACIONES = base.CreateObjectSet<VALORACIONES>("VALORACIONES");
                }
                return _VALORACIONES;
            }
        }
        private ObjectSet<VALORACIONES> _VALORACIONES;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet AMIGOS. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToAMIGOS(AMIGOS aMIGOS)
        {
            base.AddObject("AMIGOS", aMIGOS);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet CUENTAS. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToCUENTAS(CUENTAS cUENTAS)
        {
            base.AddObject("CUENTAS", cUENTAS);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet DETALLES. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToDETALLES(DETALLES dETALLES)
        {
            base.AddObject("DETALLES", dETALLES);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet PEDIDOS. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToPEDIDOS(PEDIDOS pEDIDOS)
        {
            base.AddObject("PEDIDOS", pEDIDOS);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet PRODUCTOS. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToPRODUCTOS(PRODUCTOS pRODUCTOS)
        {
            base.AddObject("PRODUCTOS", pRODUCTOS);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet sysdiagrams. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet TIPOS_CUENTA. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToTIPOS_CUENTA(TIPOS_CUENTA tIPOS_CUENTA)
        {
            base.AddObject("TIPOS_CUENTA", tIPOS_CUENTA);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet USUARIOS. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToUSUARIOS(USUARIOS uSUARIOS)
        {
            base.AddObject("USUARIOS", uSUARIOS);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet VALORACIONES. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToVALORACIONES(VALORACIONES vALORACIONES)
        {
            base.AddObject("VALORACIONES", vALORACIONES);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="houseofgModel", Name="AMIGOS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AMIGOS : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto AMIGOS.
        /// </summary>
        /// <param name="aMI_ID">Valor inicial de la propiedad AMI_ID.</param>
        /// <param name="uSU_ID">Valor inicial de la propiedad USU_ID.</param>
        public static AMIGOS CreateAMIGOS(global::System.String aMI_ID, global::System.String uSU_ID)
        {
            AMIGOS aMIGOS = new AMIGOS();
            aMIGOS.AMI_ID = aMI_ID;
            aMIGOS.USU_ID = uSU_ID;
            return aMIGOS;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AMI_ID
        {
            get
            {
                return _AMI_ID;
            }
            set
            {
                if (_AMI_ID != value)
                {
                    OnAMI_IDChanging(value);
                    ReportPropertyChanging("AMI_ID");
                    _AMI_ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("AMI_ID");
                    OnAMI_IDChanged();
                }
            }
        }
        private global::System.String _AMI_ID;
        partial void OnAMI_IDChanging(global::System.String value);
        partial void OnAMI_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USU_ID
        {
            get
            {
                return _USU_ID;
            }
            set
            {
                OnUSU_IDChanging(value);
                ReportPropertyChanging("USU_ID");
                _USU_ID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USU_ID");
                OnUSU_IDChanged();
            }
        }
        private global::System.String _USU_ID;
        partial void OnUSU_IDChanging(global::System.String value);
        partial void OnUSU_IDChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("houseofgModel", "FK_AMIGOS_AGREGAN_USUARIOS", "USUARIOS")]
        public USUARIOS USUARIOS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USUARIOS>("houseofgModel.FK_AMIGOS_AGREGAN_USUARIOS", "USUARIOS").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USUARIOS>("houseofgModel.FK_AMIGOS_AGREGAN_USUARIOS", "USUARIOS").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<USUARIOS> USUARIOSReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USUARIOS>("houseofgModel.FK_AMIGOS_AGREGAN_USUARIOS", "USUARIOS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<USUARIOS>("houseofgModel.FK_AMIGOS_AGREGAN_USUARIOS", "USUARIOS", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="houseofgModel", Name="CUENTAS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CUENTAS : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto CUENTAS.
        /// </summary>
        /// <param name="cUE_ID">Valor inicial de la propiedad CUE_ID.</param>
        /// <param name="uSU_ID">Valor inicial de la propiedad USU_ID.</param>
        /// <param name="tIC_ID">Valor inicial de la propiedad TIC_ID.</param>
        /// <param name="cUE_PASSWORD">Valor inicial de la propiedad CUE_PASSWORD.</param>
        public static CUENTAS CreateCUENTAS(global::System.Int32 cUE_ID, global::System.String uSU_ID, global::System.Int32 tIC_ID, global::System.String cUE_PASSWORD)
        {
            CUENTAS cUENTAS = new CUENTAS();
            cUENTAS.CUE_ID = cUE_ID;
            cUENTAS.USU_ID = uSU_ID;
            cUENTAS.TIC_ID = tIC_ID;
            cUENTAS.CUE_PASSWORD = cUE_PASSWORD;
            return cUENTAS;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CUE_ID
        {
            get
            {
                return _CUE_ID;
            }
            set
            {
                if (_CUE_ID != value)
                {
                    OnCUE_IDChanging(value);
                    ReportPropertyChanging("CUE_ID");
                    _CUE_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CUE_ID");
                    OnCUE_IDChanged();
                }
            }
        }
        private global::System.Int32 _CUE_ID;
        partial void OnCUE_IDChanging(global::System.Int32 value);
        partial void OnCUE_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USU_ID
        {
            get
            {
                return _USU_ID;
            }
            set
            {
                OnUSU_IDChanging(value);
                ReportPropertyChanging("USU_ID");
                _USU_ID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USU_ID");
                OnUSU_IDChanged();
            }
        }
        private global::System.String _USU_ID;
        partial void OnUSU_IDChanging(global::System.String value);
        partial void OnUSU_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TIC_ID
        {
            get
            {
                return _TIC_ID;
            }
            set
            {
                OnTIC_IDChanging(value);
                ReportPropertyChanging("TIC_ID");
                _TIC_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TIC_ID");
                OnTIC_IDChanged();
            }
        }
        private global::System.Int32 _TIC_ID;
        partial void OnTIC_IDChanging(global::System.Int32 value);
        partial void OnTIC_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CUE_PASSWORD
        {
            get
            {
                return _CUE_PASSWORD;
            }
            set
            {
                OnCUE_PASSWORDChanging(value);
                ReportPropertyChanging("CUE_PASSWORD");
                _CUE_PASSWORD = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CUE_PASSWORD");
                OnCUE_PASSWORDChanged();
            }
        }
        private global::System.String _CUE_PASSWORD;
        partial void OnCUE_PASSWORDChanging(global::System.String value);
        partial void OnCUE_PASSWORDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CUE_ESTADO
        {
            get
            {
                return _CUE_ESTADO;
            }
            set
            {
                OnCUE_ESTADOChanging(value);
                ReportPropertyChanging("CUE_ESTADO");
                _CUE_ESTADO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CUE_ESTADO");
                OnCUE_ESTADOChanged();
            }
        }
        private Nullable<global::System.Int32> _CUE_ESTADO;
        partial void OnCUE_ESTADOChanging(Nullable<global::System.Int32> value);
        partial void OnCUE_ESTADOChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("houseofgModel", "FK_CUENTAS_CONTIENEN_TIPOS_CU", "TIPOS_CUENTA")]
        public TIPOS_CUENTA TIPOS_CUENTA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TIPOS_CUENTA>("houseofgModel.FK_CUENTAS_CONTIENEN_TIPOS_CU", "TIPOS_CUENTA").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TIPOS_CUENTA>("houseofgModel.FK_CUENTAS_CONTIENEN_TIPOS_CU", "TIPOS_CUENTA").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TIPOS_CUENTA> TIPOS_CUENTAReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TIPOS_CUENTA>("houseofgModel.FK_CUENTAS_CONTIENEN_TIPOS_CU", "TIPOS_CUENTA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TIPOS_CUENTA>("houseofgModel.FK_CUENTAS_CONTIENEN_TIPOS_CU", "TIPOS_CUENTA", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("houseofgModel", "FK_CUENTAS_CREAN_USUARIOS", "USUARIOS")]
        public USUARIOS USUARIOS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USUARIOS>("houseofgModel.FK_CUENTAS_CREAN_USUARIOS", "USUARIOS").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USUARIOS>("houseofgModel.FK_CUENTAS_CREAN_USUARIOS", "USUARIOS").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<USUARIOS> USUARIOSReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USUARIOS>("houseofgModel.FK_CUENTAS_CREAN_USUARIOS", "USUARIOS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<USUARIOS>("houseofgModel.FK_CUENTAS_CREAN_USUARIOS", "USUARIOS", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="houseofgModel", Name="DETALLES")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DETALLES : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto DETALLES.
        /// </summary>
        /// <param name="dET_ID">Valor inicial de la propiedad DET_ID.</param>
        /// <param name="pROD_ID">Valor inicial de la propiedad PROD_ID.</param>
        /// <param name="pED_ID">Valor inicial de la propiedad PED_ID.</param>
        /// <param name="dET_CANTIDAD">Valor inicial de la propiedad DET_CANTIDAD.</param>
        public static DETALLES CreateDETALLES(global::System.Int32 dET_ID, global::System.Int32 pROD_ID, global::System.Int32 pED_ID, global::System.Int32 dET_CANTIDAD)
        {
            DETALLES dETALLES = new DETALLES();
            dETALLES.DET_ID = dET_ID;
            dETALLES.PROD_ID = pROD_ID;
            dETALLES.PED_ID = pED_ID;
            dETALLES.DET_CANTIDAD = dET_CANTIDAD;
            return dETALLES;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DET_ID
        {
            get
            {
                return _DET_ID;
            }
            set
            {
                if (_DET_ID != value)
                {
                    OnDET_IDChanging(value);
                    ReportPropertyChanging("DET_ID");
                    _DET_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DET_ID");
                    OnDET_IDChanged();
                }
            }
        }
        private global::System.Int32 _DET_ID;
        partial void OnDET_IDChanging(global::System.Int32 value);
        partial void OnDET_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PROD_ID
        {
            get
            {
                return _PROD_ID;
            }
            set
            {
                OnPROD_IDChanging(value);
                ReportPropertyChanging("PROD_ID");
                _PROD_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PROD_ID");
                OnPROD_IDChanged();
            }
        }
        private global::System.Int32 _PROD_ID;
        partial void OnPROD_IDChanging(global::System.Int32 value);
        partial void OnPROD_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PED_ID
        {
            get
            {
                return _PED_ID;
            }
            set
            {
                OnPED_IDChanging(value);
                ReportPropertyChanging("PED_ID");
                _PED_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PED_ID");
                OnPED_IDChanged();
            }
        }
        private global::System.Int32 _PED_ID;
        partial void OnPED_IDChanging(global::System.Int32 value);
        partial void OnPED_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DET_CANTIDAD
        {
            get
            {
                return _DET_CANTIDAD;
            }
            set
            {
                OnDET_CANTIDADChanging(value);
                ReportPropertyChanging("DET_CANTIDAD");
                _DET_CANTIDAD = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DET_CANTIDAD");
                OnDET_CANTIDADChanged();
            }
        }
        private global::System.Int32 _DET_CANTIDAD;
        partial void OnDET_CANTIDADChanging(global::System.Int32 value);
        partial void OnDET_CANTIDADChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DET_PAGADO
        {
            get
            {
                return _DET_PAGADO;
            }
            set
            {
                OnDET_PAGADOChanging(value);
                ReportPropertyChanging("DET_PAGADO");
                _DET_PAGADO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DET_PAGADO");
                OnDET_PAGADOChanged();
            }
        }
        private Nullable<global::System.Int32> _DET_PAGADO;
        partial void OnDET_PAGADOChanging(Nullable<global::System.Int32> value);
        partial void OnDET_PAGADOChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("houseofgModel", "FK_DETALLES_GENERAN_PRODUCTO", "PRODUCTOS")]
        public PRODUCTOS PRODUCTOS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PRODUCTOS>("houseofgModel.FK_DETALLES_GENERAN_PRODUCTO", "PRODUCTOS").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PRODUCTOS>("houseofgModel.FK_DETALLES_GENERAN_PRODUCTO", "PRODUCTOS").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PRODUCTOS> PRODUCTOSReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PRODUCTOS>("houseofgModel.FK_DETALLES_GENERAN_PRODUCTO", "PRODUCTOS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PRODUCTOS>("houseofgModel.FK_DETALLES_GENERAN_PRODUCTO", "PRODUCTOS", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("houseofgModel", "FK_DETALLES_POSEE_PEDIDOS", "PEDIDOS")]
        public PEDIDOS PEDIDOS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PEDIDOS>("houseofgModel.FK_DETALLES_POSEE_PEDIDOS", "PEDIDOS").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PEDIDOS>("houseofgModel.FK_DETALLES_POSEE_PEDIDOS", "PEDIDOS").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PEDIDOS> PEDIDOSReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PEDIDOS>("houseofgModel.FK_DETALLES_POSEE_PEDIDOS", "PEDIDOS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PEDIDOS>("houseofgModel.FK_DETALLES_POSEE_PEDIDOS", "PEDIDOS", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="houseofgModel", Name="PEDIDOS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PEDIDOS : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto PEDIDOS.
        /// </summary>
        /// <param name="pED_ID">Valor inicial de la propiedad PED_ID.</param>
        /// <param name="uSU_ID">Valor inicial de la propiedad USU_ID.</param>
        /// <param name="pED_FECHA">Valor inicial de la propiedad PED_FECHA.</param>
        public static PEDIDOS CreatePEDIDOS(global::System.Int32 pED_ID, global::System.String uSU_ID, global::System.DateTime pED_FECHA)
        {
            PEDIDOS pEDIDOS = new PEDIDOS();
            pEDIDOS.PED_ID = pED_ID;
            pEDIDOS.USU_ID = uSU_ID;
            pEDIDOS.PED_FECHA = pED_FECHA;
            return pEDIDOS;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PED_ID
        {
            get
            {
                return _PED_ID;
            }
            set
            {
                if (_PED_ID != value)
                {
                    OnPED_IDChanging(value);
                    ReportPropertyChanging("PED_ID");
                    _PED_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PED_ID");
                    OnPED_IDChanged();
                }
            }
        }
        private global::System.Int32 _PED_ID;
        partial void OnPED_IDChanging(global::System.Int32 value);
        partial void OnPED_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USU_ID
        {
            get
            {
                return _USU_ID;
            }
            set
            {
                OnUSU_IDChanging(value);
                ReportPropertyChanging("USU_ID");
                _USU_ID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USU_ID");
                OnUSU_IDChanged();
            }
        }
        private global::System.String _USU_ID;
        partial void OnUSU_IDChanging(global::System.String value);
        partial void OnUSU_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime PED_FECHA
        {
            get
            {
                return _PED_FECHA;
            }
            set
            {
                OnPED_FECHAChanging(value);
                ReportPropertyChanging("PED_FECHA");
                _PED_FECHA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PED_FECHA");
                OnPED_FECHAChanged();
            }
        }
        private global::System.DateTime _PED_FECHA;
        partial void OnPED_FECHAChanging(global::System.DateTime value);
        partial void OnPED_FECHAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PED_ESTADO
        {
            get
            {
                return _PED_ESTADO;
            }
            set
            {
                OnPED_ESTADOChanging(value);
                ReportPropertyChanging("PED_ESTADO");
                _PED_ESTADO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PED_ESTADO");
                OnPED_ESTADOChanged();
            }
        }
        private Nullable<global::System.Int32> _PED_ESTADO;
        partial void OnPED_ESTADOChanging(Nullable<global::System.Int32> value);
        partial void OnPED_ESTADOChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("houseofgModel", "FK_DETALLES_POSEE_PEDIDOS", "DETALLES")]
        public EntityCollection<DETALLES> DETALLES
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DETALLES>("houseofgModel.FK_DETALLES_POSEE_PEDIDOS", "DETALLES");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DETALLES>("houseofgModel.FK_DETALLES_POSEE_PEDIDOS", "DETALLES", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("houseofgModel", "FK_PEDIDOS_REALIZA_USUARIOS", "USUARIOS")]
        public USUARIOS USUARIOS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USUARIOS>("houseofgModel.FK_PEDIDOS_REALIZA_USUARIOS", "USUARIOS").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USUARIOS>("houseofgModel.FK_PEDIDOS_REALIZA_USUARIOS", "USUARIOS").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<USUARIOS> USUARIOSReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USUARIOS>("houseofgModel.FK_PEDIDOS_REALIZA_USUARIOS", "USUARIOS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<USUARIOS>("houseofgModel.FK_PEDIDOS_REALIZA_USUARIOS", "USUARIOS", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="houseofgModel", Name="PRODUCTOS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PRODUCTOS : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto PRODUCTOS.
        /// </summary>
        /// <param name="pROD_ID">Valor inicial de la propiedad PROD_ID.</param>
        /// <param name="pROD_DISPONIBLE">Valor inicial de la propiedad PROD_DISPONIBLE.</param>
        /// <param name="pROD_STOCK">Valor inicial de la propiedad PROD_STOCK.</param>
        /// <param name="pROD_DESCRIPCIONCORTA">Valor inicial de la propiedad PROD_DESCRIPCIONCORTA.</param>
        /// <param name="pROD_PRECIO">Valor inicial de la propiedad PROD_PRECIO.</param>
        /// <param name="pROD_NOMBRE">Valor inicial de la propiedad PROD_NOMBRE.</param>
        public static PRODUCTOS CreatePRODUCTOS(global::System.Int32 pROD_ID, global::System.Int32 pROD_DISPONIBLE, global::System.Int32 pROD_STOCK, global::System.String pROD_DESCRIPCIONCORTA, global::System.Int32 pROD_PRECIO, global::System.String pROD_NOMBRE)
        {
            PRODUCTOS pRODUCTOS = new PRODUCTOS();
            pRODUCTOS.PROD_ID = pROD_ID;
            pRODUCTOS.PROD_DISPONIBLE = pROD_DISPONIBLE;
            pRODUCTOS.PROD_STOCK = pROD_STOCK;
            pRODUCTOS.PROD_DESCRIPCIONCORTA = pROD_DESCRIPCIONCORTA;
            pRODUCTOS.PROD_PRECIO = pROD_PRECIO;
            pRODUCTOS.PROD_NOMBRE = pROD_NOMBRE;
            return pRODUCTOS;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PROD_ID
        {
            get
            {
                return _PROD_ID;
            }
            set
            {
                if (_PROD_ID != value)
                {
                    OnPROD_IDChanging(value);
                    ReportPropertyChanging("PROD_ID");
                    _PROD_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PROD_ID");
                    OnPROD_IDChanged();
                }
            }
        }
        private global::System.Int32 _PROD_ID;
        partial void OnPROD_IDChanging(global::System.Int32 value);
        partial void OnPROD_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PROD_DISPONIBLE
        {
            get
            {
                return _PROD_DISPONIBLE;
            }
            set
            {
                OnPROD_DISPONIBLEChanging(value);
                ReportPropertyChanging("PROD_DISPONIBLE");
                _PROD_DISPONIBLE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PROD_DISPONIBLE");
                OnPROD_DISPONIBLEChanged();
            }
        }
        private global::System.Int32 _PROD_DISPONIBLE;
        partial void OnPROD_DISPONIBLEChanging(global::System.Int32 value);
        partial void OnPROD_DISPONIBLEChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PROD_STOCK
        {
            get
            {
                return _PROD_STOCK;
            }
            set
            {
                OnPROD_STOCKChanging(value);
                ReportPropertyChanging("PROD_STOCK");
                _PROD_STOCK = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PROD_STOCK");
                OnPROD_STOCKChanged();
            }
        }
        private global::System.Int32 _PROD_STOCK;
        partial void OnPROD_STOCKChanging(global::System.Int32 value);
        partial void OnPROD_STOCKChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PROD_IMAGEN
        {
            get
            {
                return _PROD_IMAGEN;
            }
            set
            {
                OnPROD_IMAGENChanging(value);
                ReportPropertyChanging("PROD_IMAGEN");
                _PROD_IMAGEN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PROD_IMAGEN");
                OnPROD_IMAGENChanged();
            }
        }
        private global::System.String _PROD_IMAGEN;
        partial void OnPROD_IMAGENChanging(global::System.String value);
        partial void OnPROD_IMAGENChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PROD_DESCRIPCIONCORTA
        {
            get
            {
                return _PROD_DESCRIPCIONCORTA;
            }
            set
            {
                OnPROD_DESCRIPCIONCORTAChanging(value);
                ReportPropertyChanging("PROD_DESCRIPCIONCORTA");
                _PROD_DESCRIPCIONCORTA = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PROD_DESCRIPCIONCORTA");
                OnPROD_DESCRIPCIONCORTAChanged();
            }
        }
        private global::System.String _PROD_DESCRIPCIONCORTA;
        partial void OnPROD_DESCRIPCIONCORTAChanging(global::System.String value);
        partial void OnPROD_DESCRIPCIONCORTAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PROD_PRECIO
        {
            get
            {
                return _PROD_PRECIO;
            }
            set
            {
                OnPROD_PRECIOChanging(value);
                ReportPropertyChanging("PROD_PRECIO");
                _PROD_PRECIO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PROD_PRECIO");
                OnPROD_PRECIOChanged();
            }
        }
        private global::System.Int32 _PROD_PRECIO;
        partial void OnPROD_PRECIOChanging(global::System.Int32 value);
        partial void OnPROD_PRECIOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PROD_DESCRIPCIONCOMPLETA
        {
            get
            {
                return _PROD_DESCRIPCIONCOMPLETA;
            }
            set
            {
                OnPROD_DESCRIPCIONCOMPLETAChanging(value);
                ReportPropertyChanging("PROD_DESCRIPCIONCOMPLETA");
                _PROD_DESCRIPCIONCOMPLETA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PROD_DESCRIPCIONCOMPLETA");
                OnPROD_DESCRIPCIONCOMPLETAChanged();
            }
        }
        private global::System.String _PROD_DESCRIPCIONCOMPLETA;
        partial void OnPROD_DESCRIPCIONCOMPLETAChanging(global::System.String value);
        partial void OnPROD_DESCRIPCIONCOMPLETAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PROD_NOMBRE
        {
            get
            {
                return _PROD_NOMBRE;
            }
            set
            {
                OnPROD_NOMBREChanging(value);
                ReportPropertyChanging("PROD_NOMBRE");
                _PROD_NOMBRE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PROD_NOMBRE");
                OnPROD_NOMBREChanged();
            }
        }
        private global::System.String _PROD_NOMBRE;
        partial void OnPROD_NOMBREChanging(global::System.String value);
        partial void OnPROD_NOMBREChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("houseofgModel", "FK_DETALLES_GENERAN_PRODUCTO", "DETALLES")]
        public EntityCollection<DETALLES> DETALLES
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DETALLES>("houseofgModel.FK_DETALLES_GENERAN_PRODUCTO", "DETALLES");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DETALLES>("houseofgModel.FK_DETALLES_GENERAN_PRODUCTO", "DETALLES", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("houseofgModel", "FK_VALORACI_TIENEN_PRODUCTO", "VALORACIONES")]
        public EntityCollection<VALORACIONES> VALORACIONES
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<VALORACIONES>("houseofgModel.FK_VALORACI_TIENEN_PRODUCTO", "VALORACIONES");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<VALORACIONES>("houseofgModel.FK_VALORACI_TIENEN_PRODUCTO", "VALORACIONES", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="houseofgModel", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto sysdiagrams.
        /// </summary>
        /// <param name="name">Valor inicial de la propiedad name.</param>
        /// <param name="principal_id">Valor inicial de la propiedad principal_id.</param>
        /// <param name="diagram_id">Valor inicial de la propiedad diagram_id.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="houseofgModel", Name="TIPOS_CUENTA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TIPOS_CUENTA : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto TIPOS_CUENTA.
        /// </summary>
        /// <param name="tIC_ID">Valor inicial de la propiedad TIC_ID.</param>
        /// <param name="tIC_NOMBRE">Valor inicial de la propiedad TIC_NOMBRE.</param>
        public static TIPOS_CUENTA CreateTIPOS_CUENTA(global::System.Int32 tIC_ID, global::System.String tIC_NOMBRE)
        {
            TIPOS_CUENTA tIPOS_CUENTA = new TIPOS_CUENTA();
            tIPOS_CUENTA.TIC_ID = tIC_ID;
            tIPOS_CUENTA.TIC_NOMBRE = tIC_NOMBRE;
            return tIPOS_CUENTA;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TIC_ID
        {
            get
            {
                return _TIC_ID;
            }
            set
            {
                if (_TIC_ID != value)
                {
                    OnTIC_IDChanging(value);
                    ReportPropertyChanging("TIC_ID");
                    _TIC_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TIC_ID");
                    OnTIC_IDChanged();
                }
            }
        }
        private global::System.Int32 _TIC_ID;
        partial void OnTIC_IDChanging(global::System.Int32 value);
        partial void OnTIC_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TIC_NOMBRE
        {
            get
            {
                return _TIC_NOMBRE;
            }
            set
            {
                OnTIC_NOMBREChanging(value);
                ReportPropertyChanging("TIC_NOMBRE");
                _TIC_NOMBRE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TIC_NOMBRE");
                OnTIC_NOMBREChanged();
            }
        }
        private global::System.String _TIC_NOMBRE;
        partial void OnTIC_NOMBREChanging(global::System.String value);
        partial void OnTIC_NOMBREChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("houseofgModel", "FK_CUENTAS_CONTIENEN_TIPOS_CU", "CUENTAS")]
        public EntityCollection<CUENTAS> CUENTAS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CUENTAS>("houseofgModel.FK_CUENTAS_CONTIENEN_TIPOS_CU", "CUENTAS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CUENTAS>("houseofgModel.FK_CUENTAS_CONTIENEN_TIPOS_CU", "CUENTAS", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="houseofgModel", Name="USUARIOS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class USUARIOS : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto USUARIOS.
        /// </summary>
        /// <param name="uSU_ID">Valor inicial de la propiedad USU_ID.</param>
        /// <param name="uSU_NOMBRE">Valor inicial de la propiedad USU_NOMBRE.</param>
        /// <param name="uSU_APELLIDO">Valor inicial de la propiedad USU_APELLIDO.</param>
        /// <param name="uSU_DIRECCION">Valor inicial de la propiedad USU_DIRECCION.</param>
        /// <param name="uSU_EMAIL">Valor inicial de la propiedad USU_EMAIL.</param>
        /// <param name="uSU_CIUDAD">Valor inicial de la propiedad USU_CIUDAD.</param>
        public static USUARIOS CreateUSUARIOS(global::System.String uSU_ID, global::System.String uSU_NOMBRE, global::System.String uSU_APELLIDO, global::System.String uSU_DIRECCION, global::System.String uSU_EMAIL, global::System.String uSU_CIUDAD)
        {
            USUARIOS uSUARIOS = new USUARIOS();
            uSUARIOS.USU_ID = uSU_ID;
            uSUARIOS.USU_NOMBRE = uSU_NOMBRE;
            uSUARIOS.USU_APELLIDO = uSU_APELLIDO;
            uSUARIOS.USU_DIRECCION = uSU_DIRECCION;
            uSUARIOS.USU_EMAIL = uSU_EMAIL;
            uSUARIOS.USU_CIUDAD = uSU_CIUDAD;
            return uSUARIOS;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USU_ID
        {
            get
            {
                return _USU_ID;
            }
            set
            {
                if (_USU_ID != value)
                {
                    OnUSU_IDChanging(value);
                    ReportPropertyChanging("USU_ID");
                    _USU_ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("USU_ID");
                    OnUSU_IDChanged();
                }
            }
        }
        private global::System.String _USU_ID;
        partial void OnUSU_IDChanging(global::System.String value);
        partial void OnUSU_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USU_NOMBRE
        {
            get
            {
                return _USU_NOMBRE;
            }
            set
            {
                OnUSU_NOMBREChanging(value);
                ReportPropertyChanging("USU_NOMBRE");
                _USU_NOMBRE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USU_NOMBRE");
                OnUSU_NOMBREChanged();
            }
        }
        private global::System.String _USU_NOMBRE;
        partial void OnUSU_NOMBREChanging(global::System.String value);
        partial void OnUSU_NOMBREChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USU_APELLIDO
        {
            get
            {
                return _USU_APELLIDO;
            }
            set
            {
                OnUSU_APELLIDOChanging(value);
                ReportPropertyChanging("USU_APELLIDO");
                _USU_APELLIDO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USU_APELLIDO");
                OnUSU_APELLIDOChanged();
            }
        }
        private global::System.String _USU_APELLIDO;
        partial void OnUSU_APELLIDOChanging(global::System.String value);
        partial void OnUSU_APELLIDOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USU_DIRECCION
        {
            get
            {
                return _USU_DIRECCION;
            }
            set
            {
                OnUSU_DIRECCIONChanging(value);
                ReportPropertyChanging("USU_DIRECCION");
                _USU_DIRECCION = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USU_DIRECCION");
                OnUSU_DIRECCIONChanged();
            }
        }
        private global::System.String _USU_DIRECCION;
        partial void OnUSU_DIRECCIONChanging(global::System.String value);
        partial void OnUSU_DIRECCIONChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USU_EMAIL
        {
            get
            {
                return _USU_EMAIL;
            }
            set
            {
                OnUSU_EMAILChanging(value);
                ReportPropertyChanging("USU_EMAIL");
                _USU_EMAIL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USU_EMAIL");
                OnUSU_EMAILChanged();
            }
        }
        private global::System.String _USU_EMAIL;
        partial void OnUSU_EMAILChanging(global::System.String value);
        partial void OnUSU_EMAILChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USU_CIUDAD
        {
            get
            {
                return _USU_CIUDAD;
            }
            set
            {
                OnUSU_CIUDADChanging(value);
                ReportPropertyChanging("USU_CIUDAD");
                _USU_CIUDAD = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USU_CIUDAD");
                OnUSU_CIUDADChanged();
            }
        }
        private global::System.String _USU_CIUDAD;
        partial void OnUSU_CIUDADChanging(global::System.String value);
        partial void OnUSU_CIUDADChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("houseofgModel", "FK_AMIGOS_AGREGAN_USUARIOS", "AMIGOS")]
        public EntityCollection<AMIGOS> AMIGOS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<AMIGOS>("houseofgModel.FK_AMIGOS_AGREGAN_USUARIOS", "AMIGOS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<AMIGOS>("houseofgModel.FK_AMIGOS_AGREGAN_USUARIOS", "AMIGOS", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("houseofgModel", "FK_CUENTAS_CREAN_USUARIOS", "CUENTAS")]
        public EntityCollection<CUENTAS> CUENTAS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CUENTAS>("houseofgModel.FK_CUENTAS_CREAN_USUARIOS", "CUENTAS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CUENTAS>("houseofgModel.FK_CUENTAS_CREAN_USUARIOS", "CUENTAS", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("houseofgModel", "FK_PEDIDOS_REALIZA_USUARIOS", "PEDIDOS")]
        public EntityCollection<PEDIDOS> PEDIDOS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PEDIDOS>("houseofgModel.FK_PEDIDOS_REALIZA_USUARIOS", "PEDIDOS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PEDIDOS>("houseofgModel.FK_PEDIDOS_REALIZA_USUARIOS", "PEDIDOS", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("houseofgModel", "FK_VALORACI_REALIZAN_USUARIOS", "VALORACIONES")]
        public EntityCollection<VALORACIONES> VALORACIONES
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<VALORACIONES>("houseofgModel.FK_VALORACI_REALIZAN_USUARIOS", "VALORACIONES");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<VALORACIONES>("houseofgModel.FK_VALORACI_REALIZAN_USUARIOS", "VALORACIONES", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="houseofgModel", Name="VALORACIONES")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VALORACIONES : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto VALORACIONES.
        /// </summary>
        /// <param name="vAL_ID">Valor inicial de la propiedad VAL_ID.</param>
        /// <param name="vAL_PUNTAJE">Valor inicial de la propiedad VAL_PUNTAJE.</param>
        /// <param name="vAL_COMENTARIO">Valor inicial de la propiedad VAL_COMENTARIO.</param>
        public static VALORACIONES CreateVALORACIONES(global::System.Int32 vAL_ID, global::System.Int32 vAL_PUNTAJE, global::System.String vAL_COMENTARIO)
        {
            VALORACIONES vALORACIONES = new VALORACIONES();
            vALORACIONES.VAL_ID = vAL_ID;
            vALORACIONES.VAL_PUNTAJE = vAL_PUNTAJE;
            vALORACIONES.VAL_COMENTARIO = vAL_COMENTARIO;
            return vALORACIONES;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VAL_ID
        {
            get
            {
                return _VAL_ID;
            }
            set
            {
                if (_VAL_ID != value)
                {
                    OnVAL_IDChanging(value);
                    ReportPropertyChanging("VAL_ID");
                    _VAL_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("VAL_ID");
                    OnVAL_IDChanged();
                }
            }
        }
        private global::System.Int32 _VAL_ID;
        partial void OnVAL_IDChanging(global::System.Int32 value);
        partial void OnVAL_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PROD_ID
        {
            get
            {
                return _PROD_ID;
            }
            set
            {
                OnPROD_IDChanging(value);
                ReportPropertyChanging("PROD_ID");
                _PROD_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PROD_ID");
                OnPROD_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _PROD_ID;
        partial void OnPROD_IDChanging(Nullable<global::System.Int32> value);
        partial void OnPROD_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String USU_ID
        {
            get
            {
                return _USU_ID;
            }
            set
            {
                OnUSU_IDChanging(value);
                ReportPropertyChanging("USU_ID");
                _USU_ID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("USU_ID");
                OnUSU_IDChanged();
            }
        }
        private global::System.String _USU_ID;
        partial void OnUSU_IDChanging(global::System.String value);
        partial void OnUSU_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VAL_PUNTAJE
        {
            get
            {
                return _VAL_PUNTAJE;
            }
            set
            {
                OnVAL_PUNTAJEChanging(value);
                ReportPropertyChanging("VAL_PUNTAJE");
                _VAL_PUNTAJE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VAL_PUNTAJE");
                OnVAL_PUNTAJEChanged();
            }
        }
        private global::System.Int32 _VAL_PUNTAJE;
        partial void OnVAL_PUNTAJEChanging(global::System.Int32 value);
        partial void OnVAL_PUNTAJEChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String VAL_COMENTARIO
        {
            get
            {
                return _VAL_COMENTARIO;
            }
            set
            {
                OnVAL_COMENTARIOChanging(value);
                ReportPropertyChanging("VAL_COMENTARIO");
                _VAL_COMENTARIO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("VAL_COMENTARIO");
                OnVAL_COMENTARIOChanged();
            }
        }
        private global::System.String _VAL_COMENTARIO;
        partial void OnVAL_COMENTARIOChanging(global::System.String value);
        partial void OnVAL_COMENTARIOChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("houseofgModel", "FK_VALORACI_TIENEN_PRODUCTO", "PRODUCTOS")]
        public PRODUCTOS PRODUCTOS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PRODUCTOS>("houseofgModel.FK_VALORACI_TIENEN_PRODUCTO", "PRODUCTOS").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PRODUCTOS>("houseofgModel.FK_VALORACI_TIENEN_PRODUCTO", "PRODUCTOS").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PRODUCTOS> PRODUCTOSReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PRODUCTOS>("houseofgModel.FK_VALORACI_TIENEN_PRODUCTO", "PRODUCTOS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PRODUCTOS>("houseofgModel.FK_VALORACI_TIENEN_PRODUCTO", "PRODUCTOS", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("houseofgModel", "FK_VALORACI_REALIZAN_USUARIOS", "USUARIOS")]
        public USUARIOS USUARIOS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USUARIOS>("houseofgModel.FK_VALORACI_REALIZAN_USUARIOS", "USUARIOS").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USUARIOS>("houseofgModel.FK_VALORACI_REALIZAN_USUARIOS", "USUARIOS").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<USUARIOS> USUARIOSReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USUARIOS>("houseofgModel.FK_VALORACI_REALIZAN_USUARIOS", "USUARIOS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<USUARIOS>("houseofgModel.FK_VALORACI_REALIZAN_USUARIOS", "USUARIOS", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
